[package]
name = "escape-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = { version = "0.29.0", features = ["unstable-widget-ref"] }
anyhow = "1.0.91"
lsblk = "0.4.0"
notify = "7.0.0"
tui-big-text = "0.7.0"
rand = { version = "0.8.5", features = ["small_rng"] }
awedio = "0.4.1"